server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_management?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false